### ISSUE TITLE
Density modelling

### ISSUE THREAD

**Issue by gnssgrid** [zhong-yy/GraSphInv#2]
Hi Zhong
Is it possible to use your software to create model of density based on gridded Bouguer anomalies?

**Comment by zhong-yy** [comment]
Hi, @gnssgrid. Yes, you can use Bouguer anomalies to build your density model. Note however that any density features beneath the depth of Moho can be artefacts if you use Bouguer anomalies, because Bouguer anomalies are mainly attributed to the Moho relief and heterogeneities within the crust and the poor depth resolution of gravity data can cause vertical smearing in the density model.

**Comment by gnssgrid** [comment]
Hi @zhong-yy 
Well I need density model for geoid computation. So if Bouguer anomalies are not good enough, then what is you suggestion? Free air anomalies or?

**Comment by zhong-yy** [comment]
From gravity anomalies, we can only obtain density contrasts with respect to a reference model (e.g. mass deficit and mass excess), instead of an absolute density model. For example, bouguer anomaly corresponds to the mass anomalies within the crust, and the Moho relief. Which kind of anomaly is suitable depends on which part of the earth you focus on. 

I am not familiar with geoid computation so I am not sure whether my code can be used to generate a model for geoid computation.

**Comment by gnssgrid** [comment]
Well for geoid modelling we need density of topography above geoid, ie above mean sea level.

**Comment by zhong-yy** [comment]
Maybe this code is not appropriate because it doesn't consider the topography.
